# Generated by Django 5.2.8 on 2025-11-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='abut',
        ),
    ]
