# Generated by Django 5.2.8 on 2025-11-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_abut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='qiziqishlar',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='ozodbek', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='ism',
            field=models.CharField(default='raqam', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='telefon',
            field=models.CharField(default='malumotlar@gmail.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='tugilgan_sana',
            field=models.DateField(default=1231),
            preserve_default=False,
        ),
    ]
